import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import {
  ERROR_CODES,
  LoomError,
  brandWarnings,
  composePackageJson,
  readInputFile,
  renderDirectory,
  resolveBrand,
  resolveTargetDirectory,
  sha256,
  skillFiles,
  stringifyJson,
  validateOptions,
} from '@link-loom/devkit';

import entityGenerator from '../entity/index.js';
import { composeEnv } from './compose/env.js';
import { dictionaryModule, fillTokens, mergeDictionaries } from './compose/dictionary.js';
import { authGradientFor, brandFiles } from './compose/brand-files.js';
import { headerArtwork, themeModule } from './compose/theme.js';

const here = (relative) => fileURLToPath(new URL(relative, import.meta.url));
const readJson = (file) => JSON.parse(fs.readFileSync(file, 'utf8'));

const LAYERS_DIR = here('./layers/');
const SKILL_NAME = 'loom-react';
const SKILL_DIR = here(`../../../skills/${SKILL_NAME}/`);
const STACK = readJson(here('../../stack.json'));
const COLLECTION_VERSION = readJson(here('../../../package.json')).version;

export const LAYER_IDS = Object.freeze({
  base: 'base',
  signup: 'signup',
  stoneos: 'stoneos',
  commandCenter: 'command-center',
});

const ENTITY_SCHEMA = readJson(here('../entity/schema.json'));

/**
 * The CRUD every app is born with, generated by `add entity` like any later one: the platform's own API keys
 * (the contract of /security/api-key), under Advanced settings, with copy, rotate and revoke.
 */
export const apiKeysEntity = (name) =>
  validateOptions(ENTITY_SCHEMA, {
    domain: 'security',
    entity: 'api-key',
    plural: 'api-keys',
    singularEn: 'API key',
    pluralEn: 'API keys',
    singularEs: 'Clave de API',
    pluralEs: 'Claves de API',
    genderEs: 'f',
    descriptionEn: `The keys other systems use to call ${name}. Rotate one that may have leaked; revoke the ones nobody uses.`,
    descriptionEs: `Las claves con las que otros sistemas llaman a ${name}. Rota la que pudo filtrarse; revoca las que nadie usa.`,
    fields: ['name:text:required', 'key:secret:list'],
    fieldLabelsEn: ['name=Name', 'key=Key'],
    fieldLabelsEs: ['name=Nombre', 'key=Clave'],
    list: 'standard',
    actions: ['quickview', 'copy-id', 'delete'],
    customActions: ['rotate:replace'],
    actionLabelsEn: ['rotate=Rotate', 'delete=Revoke'],
    actionLabelsEs: ['rotate=Rotar', 'delete=Revocar'],
    endpoint: '/security/api-key',
    scope: 'organization',
    createDefaults: ['project_id={slug}'],
    icon: 'keys',
    section: 'advanced',
    navigation: false,
    omnisearch: false,
    quickAdd: false,
  });

const AGENT_SKILL_DIRS = Object.freeze([`.claude/skills/${SKILL_NAME}`, `.agent/skills/${SKILL_NAME}`]);

const DICTIONARY_HEADER = {
  en: '// Every text people see in the app. es.js has exactly the same keys; `npm test` checks it.',
  es: '// Todos los textos visibles de la app. en.js tiene exactamente las mismas claves; `npm test` lo verifica.',
};

export const slugify = (value) =>
  String(value)
    .normalize('NFD')
    .replace(/[̀-ͯ]/g, '')
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');

const activeLayerIds = (options) =>
  [
    LAYER_IDS.base,
    options.signup && LAYER_IDS.signup,
    options.stoneos && LAYER_IDS.stoneos,
    options.commandCenter && LAYER_IDS.commandCenter,
  ].filter(Boolean);

const loadLayer = (id) => {
  const dir = path.join(LAYERS_DIR, id);
  const i18nFile = path.join(dir, 'i18n.json');
  return {
    ...readJson(path.join(dir, 'layer.json')),
    filesDir: path.join(dir, 'files'),
    i18n: fs.existsSync(i18nFile) ? readJson(i18nFile) : { en: {}, es: {} },
  };
};

const brandFrom = (options, slug) =>
  resolveBrand({
    mode: options.brandMode,
    preset: options.brandPreset,
    seed: options.seed ?? slug,
    colors: {
      primary: options.primaryColor,
      header: options.headerColor,
      logoArea: options.logoAreaColor,
      background: options.backgroundColor,
      footer: options.footerColor,
    },
  });

const loomManifest = ({ options, slug, basePath, layerIds, brand }) => ({
  $schema: 'https://linkloom.io/schemas/loom.json',
  type: 'webapp',
  variant: options.variant,
  slug,
  name: options.name,
  basePath,
  collection: { name: '@link-loom/react-generators', version: COLLECTION_VERSION },
  layers: layerIds,
  platforms: options.platforms,
  brand: { colors: brand, artwork: options.logo ? 'custom' : 'generated', customMark: Boolean(options.mark) },
  // What `link-loom skills sync` compares against: a file whose hash changed was edited by hand.
  skills: {
    [SKILL_NAME]: {
      version: COLLECTION_VERSION,
      files: Object.fromEntries(skillFiles(SKILL_DIR).map(({ file, content }) => [file, sha256(content)])),
    },
  },
  conventions: {
    pages: 'src/pages/<domain>/<Domain><Name>.page.jsx',
    components:
      'src/components/pages/<domain>/<entity>/{list,record,quick-actions}/<Domain><Entity><Role>.component.jsx',
    services: 'src/services/<domain>/<entity>/<domain>-<entity>.service.js',
    routes: 'src/routes/domains/<domain>/<domain>[-<entity>].routes.jsx',
    entityTests: 'tests/<domain>/<entity>/<domain>-<entity>.flow.test.jsx',
    tests: 'tests/<same path as in src>/<File>.test.jsx',
  },
});

/**
 * `create webapp`: the app frame of Mi Retail workspace, rebuilt on @link-loom/react-shell, with the layers the
 * person chose. Everything is written to the virtual tree; nothing touches the disk until the plan is applied.
 */
export default async function webappGenerator(tree, options) {
  const slug = options.slug || slugify(options.name);
  if (!slug) {
    throw new LoomError(ERROR_CODES.validation, 'The name has no letters or digits to build a slug from; pass --slug', {
      problems: [{ field: 'slug', message: 'cannot be derived from the name' }],
    });
  }

  const directory = resolveTargetDirectory(tree, { directory: options.directory, slug });

  const layerIds = activeLayerIds(options);
  const layers = layerIds.map(loadLayer);
  const brand = brandFrom(options, slug);
  const basePath = `/${options.variant}`;
  const layerFlags = {
    signup: layerIds.includes(LAYER_IDS.signup),
    stoneos: layerIds.includes(LAYER_IDS.stoneos),
    commandCenter: layerIds.includes(LAYER_IDS.commandCenter),
  };

  const data = {
    name: options.name,
    slug,
    variant: options.variant,
    basePath,
    description: options.description,
    defaultLocale: options.defaultLocale,
    port: options.port,
    organizationSlug: options.organizationSlug,
    platforms: options.platforms,
    layers: layerFlags,
    headerArtwork: headerArtwork(brand),
    brand,
    authGradient: authGradientFor(brand),
    year: new Date().getFullYear(),
    json: (value) => JSON.stringify(value),
  };

  const write = (relativePath, content) =>
    tree.create(directory ? `${directory}/${relativePath}` : relativePath, content);

  for (const layer of layers) {
    for (const file of renderDirectory(layer.filesDir, data)) {
      write(file.path, file.content);
    }
  }

  write('package.json', composePackageJson({ slug, description: options.description, layers, stack: STACK }));

  const env = composeEnv({ layers, options });
  write('.env.sample', env.sample);
  write('.env.local', env.local);

  const descriptions = { en: options.description, es: options.descriptionEs || options.description };
  for (const locale of ['en', 'es']) {
    const tokens = { name: options.name, slug, basePath, description: descriptions[locale] };
    const copy = fillTokens(mergeDictionaries(layers.map((layer) => layer.i18n[locale])), tokens);
    write(`src/i18n/${locale}.js`, dictionaryModule(locale, copy, DICTIONARY_HEADER[locale]));
  }

  write('src/constants/theme.js', themeModule({ name: options.name, brand, stoneos: layerFlags.stoneos }));
  const manifest = loomManifest({ options, slug, basePath, layerIds, brand });
  write('loom.json', stringifyJson(manifest));
  await entityGenerator(tree, apiKeysEntity(options.name), { project: manifest, directory });

  const ownArtwork = {
    logo: readInputFile(tree.root, options.logo, 'logo'),
    logoDark: readInputFile(tree.root, options.logoDark, 'logoDark'),
    mark: readInputFile(tree.root, options.mark, 'mark'),
  };
  for (const file of brandFiles({
    name: options.name,
    description: options.description,
    brand,
    basePath,
    ...ownArtwork,
  })) {
    write(file.path, file.content);
  }

  for (const skillDir of AGENT_SKILL_DIRS) {
    for (const { file, content } of skillFiles(SKILL_DIR)) {
      write(`${skillDir}/${file}`, content);
    }
  }

  const spanishFallback =
    options.description && !options.descriptionEs
      ? ['Spanish copy fell back to English for the description; pass --description-es with the Spanish sentence']
      : [];
  return {
    warnings: [...brandWarnings(brand), ...spanishFallback],
    project: { directory, kind: 'webapp', variant: options.variant, slug, basePath, layers: layerIds, brand },
    next: [...(directory ? [`cd ${directory}`] : []), 'npm run dev', 'npm run verify'],
    installIn: directory,
  };
}
